name: MSBuild

on: push

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NetFramework
        uses: microsoft/setup-msbuild@v1.1
        
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
          
      - name: NuGet restore
        run: nuget restore LearningSpace.sln
        working-directory: ./LearningSpace
        shell: cmd
        
      - name: .NET Build
        run: dotnet build LearningSpace.sln
        working-directory: ./LearningSpace
        shell: cmd
      
      - name: .NET test
        run: dotnet test LearningSpace.sln
        working-directory: ./LearningSpace
        shell: cmd
