name: MSBuild

on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Run a one-line script
        run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /help'

      - run: dotnet build LearningSpace\LearningSpace.sln
      - run: dotnet test LearningSpace\LearningSpace.sln
